name: Push (dev), Pull Request
on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:
jobs:
  lint-python:
    name: Run Python lint
    uses: kuba2k2/kuba2k2/.github/workflows/lint-python.yml@master

  hacs-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration

  hassfest-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
